---

# This is a playbook for Ansible using network-engine with "show vtp status" parser.

- hosts: blocks

  roles:
  - ansible-network.network-engine

  tasks:
  - name: Run 'show vtp status'
    ios_command:
      commands:
        - show vtp status
    register: output

    #  - name: Display the output
    #    debug: var=output.stdout

  - name: Parse the output
    command_parser:
      file: "parsers/ios/show_vtp_status_parser.yml"
      content: "{{ output.stdout[0] }}"

  - name: Display the data
    debug: var=vtp_status_facts


  - name: Delete '/tmp/vtp_status_facts-[inventory_hostname].json'
    file:
      path: "/tmp/vtp_status_facts-{{ inventory_hostname }}.json"
      state: absent

  - name: Write vtp_status_facts to '/tmp/vtp_status_facts-[inventory_hostname].json'
    copy:
      content: "{{ vtp_status_facts | to_nice_json }}"
      dest: "/tmp/vtp_status_facts-{{ inventory_hostname }}.json"
