---
- hosts: blocks
  gather_facts: False
  roles:
    - role: common
    - role: interface
    - role: etherchannel
    - role: vlans
    - role: spanning-tree
    - role: ipv4
    - role: ipv6
      when: protocol_ipv6 == 'enabled'
- hosts: access
  gather_facts: False
  roles:
    - role: no-ipv4-routing
- hosts: distribution
  gather_facts: False
  roles:
    - role: ipv4-routing
    - role: ipv6-routing
      when: protocol_ipv6 == 'enabled'
    - role: fhrp
    - role: rip
      when: '"rip" in routing.ipv4'
    - role: eigrp4
      when: '"eigrp4" in routing.ipv4'
    - role: ospfv2
      when: '"ospfv2" in routing.ipv4'
    - role: eigrp6
      when:
        - '"eigrp6" in routing.ipv6'
        - protocol_ipv6 == 'enabled'
    - role: ospfv3
      when:
        - '"ospfv3" in routing.ipv6'
        - protocol_ipv6 == 'enabled'
    - role: dhcp-server
- hosts: blocks
  gather_facts: False
  roles:
    - role: write
