---
- hosts: blocks
  gather_facts: False
  roles:
    - role: common
    - role: vlans
    - role: etherchannel
    - role: interface
    - role: spanning-tree
    - role: ipv4
    - role: ipv6
- hosts: access
  gather_facts: False
  roles:
    - role: no-ipv4-routing
- hosts: distribution
  gather_facts: False
  roles:
    - role: ipv4-routing
    - role: ipv6-routing
    - role: fhrp
    - role: rip
      when: '"rip" in routing_ipv4'
    - role: eigrp4
      when: '"eigrp4" in routing_ipv4'
    - role: ospfv2
      when: '"ospfv2" in routing_ipv4'
    - role: eigrp6
      when:
        - '"eigrp6" in routing_ipv6'
    - role: ospfv3
      when:
        - '"ospfv3" in routing_ipv6'
    - role: dhcp-server
- hosts: blocks
  gather_facts: False
  roles:
    - role: write
