---

# This is a playbook for Ansible using network-engine with "show vlan brief" parser.

- hosts: blocks

  roles:
  - ansible-network.network-engine

  tasks:
  - name: Run 'show vlan brief'
    ios_command:
      commands:
        - show vlan brief
    register: output

    #  - name: Display the output
    #    debug: var=output.stdout

  - name: Parse the output
    command_parser:
      file: "parsers/ios/show_vlan_brief_parser.yml"
      content: "{{ output.stdout[0] }}"

    #  - name: Display the data
    #    debug: var=vlan_brief_facts


  - name: Delete '/tmp/vlan_brief_facts-[inventory_hostname].json'
    file:
      path: "/tmp/vlan_brief_facts-{{ inventory_hostname }}.json"
      state: absent

  - name: Write interfaces_facts to '/tmp/vlan_brief_facts-[inventory_hostname].json'
    copy:
      content: "{{ vlan_brief_facts | to_nice_json }}"
      dest: "/tmp/vlan_brief_facts-{{ inventory_hostname }}.json"
