---
# icmp_ping.yml
- hosts: end_hosts
  gather_facts: False
  tasks:
    - shell: "ping -c 1 {{ destination }}"
      when: destination | ipv4
    - shell: "ping6 -c 1 {{ destination }}"
      when: destination | ipv6
