---
- import_tasks: disable_rip.yml
  when:
    - ansible_network_os == 'ios'
  tags:
    - disable-rip
- import_tasks: disable_eigrp4.yml
  when:
    - ansible_network_os == 'ios'
  tags:
    - disable-eigrp4
- import_tasks: disable_ospfv2.yml
  when:
    - ansible_network_os == 'ios'
  tags:
    - disable-ospfv2
