---

# This is a playbook for Ansible using network-engine with "show interfaces" parser.

- hosts: cisco

  roles:
  - ansible-network.network-engine

  tasks:
  - name: Run 'show interfaces'
    ios_command:
      commands:
        - show interfaces
    register: output

    #  - name: Display the output
    #    debug: var=output.stdout

  - name: Parse the output
    command_parser:
      file: "parsers/ios/show_interfaces_parser.yml"
      content: "{{ output.stdout[0] }}"

    #  - name: Display the data
    #    debug: var=interfaces_facts


  - name: Delete '/tmp/interfaces_facts-[inventory_hostname].json'
    file:
      path: "/tmp/interfaces_facts-{{ inventory_hostname }}.json"
      state: absent

  - name: Write interfaces_facts to '/tmp/interfaces_facts-[inventory_hostname].json'
    copy:
      content: "{{ interfaces_facts | to_nice_json }}"
      dest: "/tmp/interfaces_facts-{{ inventory_hostname }}.json"
