---
- name: define the version of stp
  ios_config:
    lines: spanning-tree mode {{ stp.mode }}
  when: stp.mode is defined
- name: define the stp root primary
  ios_config:
    lines: "spanning-tree vlan {{ item }} root primary"
  loop: "{{ stp.primary }}"
  when: item is defined
- name: define the stp root secondary
  ios_config:
    lines: "spanning-tree vlan {{ item }} root secondary"
  loop: "{{ stp.secondary }}"
  when: item is defined
