---
# bipod.yml
- hosts: core
  gather_facts: False
  roles:
    - role: ios_common
    - role: ios_interface
    - role: ios_ipv4
    - role: ios_ipv6
    - role: ios_ipv4_routing
    - role: ios_ipv6_routing
    - role: ios_static_routing
    - role: ios_rip
      when: '"rip" in ipv4.routing'
    - role: ios_recursive_dns_server
    - role: ios_dhcp_server
    - role: ios_nat44
    - role: ios_write
