---
#lab_startup.yml
- name: "Start an existing lab topology"
  hosts: localhost
  gather_facts: False
  tasks:
    - name: "Open the project"
      gns3_project:
        url: "{{ gns3_url }}"
        project_name: "{{ project_name }}"
        state: opened
    - name: "Start nodes in the project"
      gns3_project:
        url: "{{ gns3_url }}"
        project_name: "{{ project_name }}"
        state: opened
        nodes_state: started
        nodes_strategy: one_by_one
