name: Ansible Lint  # feel free to pick your own name

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # Important: This sets up your GITHUB_WORKSPACE environment variable
    - uses: actions/checkout@v2
    - name: Lint Ansible Playbook
      # replace "master" with any valid ref
      uses: ansible/ansible-lint-action@master
      with:
        # targets: |
        #   playbook_1.yml
        #   playbook_2.yml
        targets: "roles/*"
        override-deps: |
          ansible
          ansible-lint
        args: ""
